name: Deploy

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4  # Using official GitHub action instead of dawidd6
      with:
        name: build-for-deploy
        path: ./publish
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List files for verification
      run: |
        ls -la ./publish
        
    # You can add deployment steps here, such as:
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'your-app-name'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish
    
    - name: Upload Deployment Artifacts (For Reference)
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: deployed-app
        path: ./publish
        retention-days: 5
