name: Deploy

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Download Build Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: build-for-deploy
        path: ./publish
        
    # You can add deployment steps here, such as:
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'your-app-name'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish
    
    - name: Upload Deployment Artifacts (For Reference)
      uses: actions/upload-artifact@v3
      with:
        name: deployed-app
        path: ./publish
        retention-days: 5
