name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4  # Updated to v4
      with:
        dotnet-version: '9.0.x'  # Using .NET 9
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4  # Using official GitHub action instead of dawidd6
      with:
        name: build-for-test
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        
    - name: List files
      run: |
        ls -la
        
    - name: Run Tests
      run: dotnet test --no-build --configuration Release --verbosity normal