name: Hello World Workflow

 

on:
  push:
  workflow_dispatch:
    # This enables manual triggering of the workflow

 

jobs:

  hello-world-job:

    runs-on: ubuntu-latest

 

    steps:

    - name: Print Hello World

      run: echo "Hello, World!"

 
